Sprint 1: Tests
piowit/employee-recognition-platform-1638892628 pull request #5
Opened 2021-12-31 15:10 UTC by piowit

**Overview:** It's time to take care of the quality of the app. There are different types of test, but don't care that much about it, because for now we'll focus on system specs which are a type of an integration tests.

- There is a factory for Kudo model
- There is a factory for Employee model
- There is a system spec that covers creating, editing and removing a kudo
- There is a system spec that covers signing up and signing in

2022-01-02 00:57 UTC, ciejj requested changes
Good job, I left some suggestions- ping me on Slack if you get stuck with fixes ;)

2022-01-02 00:57 UTC, ciejj commented on .rubocop.yml
> +    - spec/system/*
missing newline at end of file - I suggest configuring your IDE to take care of it for you ;)

2022-01-02 00:57 UTC, ciejj commented on spec/factories/kudos.rb
> +    association :receiver_of_kudo, factory: :employee
[FYI] I think it is possible to write simply:
giver_of_kudo
receiver_of_kudo
but it is simply matter of preference - if you like it in explicit way it's fine ;)

2022-01-02 00:57 UTC, ciejj commented on spec/system/employee_spec.rb
> +  it 'create user, sign up, log out, log in' do
I suggest splitting each action to separate test

2022-01-02 00:57 UTC, ciejj commented on spec/system/kudo_spec.rb
> +  it 'Setup 2 employees and crud kudo' do
Split those tests, so each kudo action is tested separately.

2022-01-02 00:59 UTC, ciejj commented on spec/system/kudo_spec.rb
> +    expect(page).to have_content 'Welcome! You have signed up successfully.'
why testing user singin/signnup in kudo tests? You already checked that in another spec :)

2022-01-02 01:01 UTC, ciejj commented on spec/system/kudo_spec.rb
> +    expect(page).to have_content 'Kudo was successfully destroyed'
You are checking, notification, but what about page contents?

2022-01-02 01:02 UTC, ciejj requested changes

2022-01-02 01:02 UTC, ciejj commented on spec/system/kudo_spec.rb
> +    click_link 'Edit'
what if, there are mote than 1 kudo on the page?  How do you know, which one you are editing?

2022-01-03 21:44 UTC, ciejj commented on spec/system/kudo_spec.rb
> +    click_link 'Log In'
FYI - there is a helper, for that:
https://sajadtorkamani.com/how-to-login-in-capybara-tests-when-using-devise/

2022-01-03 21:44 UTC, ciejj approved these changes

2022-01-03 21:49 UTC, oskarlakner commented on .solargraph.yml
> +- "app/*.rb"y
this file shouldnt be included

2022-01-03 21:49 UTC, oskarlakner commented
looks good 👍

2022-01-03 21:54 UTC, oskarlakner commented
@piowit google `global git ignore`

2022-01-03 21:55 UTC, piowit commented on .solargraph.yml
> +- "app/*.rb"y
done

2022-01-03 22:02 UTC, merged